# Generated by Django 5.2.5 on 2025-08-19 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='service',
            name='duration',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='service',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='service',
            name='short_description',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
