# Generated by Django 5.2.5 on 2025-08-24 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_customer_projectrequirement_conversation_quote_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectrequirement',
            name='complexity_level',
            field=models.CharField(blank=True, help_text='simple, medium, complex, enterprise', max_length=20),
        ),
        migrations.AddField(
            model_name='projectrequirement',
            name='detected_features',
            field=models.JSONField(blank=True, default=list, help_text='List of detected features'),
        ),
        migrations.AddField(
            model_name='projectrequirement',
            name='hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=125, max_digits=8, null=True),
        ),
    ]
