# Generated by Django 5.2.5 on 2025-08-25 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_adminsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectEstimation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200)),
                ('company_name', models.CharField(max_length=200)),
                ('company_type', models.CharField(choices=[('ngo', 'NGO'), ('startup', 'Startup'), ('social_enterprise', 'Social Enterprise (B Corp)'), ('corporate', 'Corporate'), ('government', 'Government'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField()),
                ('tech_stack', models.JSONField(default=list, help_text='Array of technologies proposed')),
                ('breakdown_details', models.JSONField(default=dict, help_text='Detailed cost breakdown')),
                ('total_estimate', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estimated_days', models.IntegerField()),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=170, max_digits=8)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('refer_agent_code', models.CharField(blank=True, help_text='Agent referral code', max_length=50)),
                ('assigned_agent', models.CharField(blank=True, max_length=200)),
                ('conversation_history', models.JSONField(default=list, help_text='Full conversation that led to estimation')),
                ('session_id', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending Confirmation'), ('confirmed', 'Confirmed by Customer'), ('revised', 'Needs Revision'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('discount_applied', models.DecimalField(decimal_places=2, default=0, help_text='Discount percentage applied', max_digits=5)),
                ('special_requirements', models.TextField(blank=True)),
                ('timeline_requirements', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estimations', to='api.customer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
