# Generated by Django 5.2.5 on 2025-08-25 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_projectestimation'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectestimation',
            name='terms_acknowledged',
            field=models.BooleanField(default=False, help_text='Customer acknowledged terms and conditions'),
        ),
        migrations.AddField(
            model_name='projectestimation',
            name='terms_acknowledged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
