# Generated by Django 5.2.5 on 2025-08-25 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_developerteam_company_developer_project_and_more'),
    ]

    operations = [
        # Handle ProjectEstimation field renames and additions
        migrations.RenameField(
            model_name='projectestimation',
            old_name='confirmed_at',
            new_name='approved_at',
        ),
        migrations.AddField(
            model_name='projectestimation',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectestimation',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
