# Generated by Django 5.2.5 on 2025-08-26 11:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_resolve_field_conflicts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectestimation',
            name='assigned_agent',
        ),
        migrations.RemoveField(
            model_name='projectestimation',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='projectestimation',
            name='rejection_reason',
        ),
        migrations.AddField(
            model_name='projectestimation',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_estimations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectestimation',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estimations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectestimation',
            name='estimation_id',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='projectestimation',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estimation', to='api.project'),
        ),
        migrations.AddField(
            model_name='projectestimation',
            name='requires_account',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='projectestimation',
            name='breakdown_details',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='projectestimation',
            name='company_type',
            field=models.CharField(default='other', max_length=50),
        ),
        migrations.AlterField(
            model_name='projectestimation',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='projectestimation',
            name='conversation_history',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='projectestimation',
            name='discount_applied',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='projectestimation',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='projectestimation',
            name='refer_agent_code',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='projectestimation',
            name='session_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='projectestimation',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending Review'), ('requires_account', 'Requires Account'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('expired', 'Expired'), ('converted_to_project', 'Converted to Project')], default='draft', max_length=30),
        ),
        migrations.AlterField(
            model_name='projectestimation',
            name='tech_stack',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='projectestimation',
            name='terms_acknowledged',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='projectestimation',
            name='timeline_requirements',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='projectestimation',
            name='total_estimate',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
