# Generated by Django 5.2.5 on 2025-08-27 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_projectestimation_assigned_agent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('position', models.CharField(max_length=200)),
                ('experience', models.CharField(choices=[('0-1', '0-1 years'), ('1-3', '1-3 years'), ('3-5', '3-5 years'), ('5-8', '5-8 years'), ('8+', '8+ years')], max_length=10)),
                ('cover_letter', models.TextField()),
                ('cv', models.FileField(help_text='Upload your CV/Resume (PDF, DOC, or DOCX format, max 5MB)', upload_to='applications/cvs/')),
                ('linkedin', models.URLField(blank=True, help_text='LinkedIn profile URL')),
                ('portfolio', models.URLField(blank=True, help_text='Portfolio or personal website URL')),
                ('status', models.CharField(choices=[('new', 'New'), ('reviewing', 'Under Review'), ('interview', 'Interview Scheduled'), ('rejected', 'Rejected'), ('accepted', 'Accepted')], default='new', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Internal notes for HR team')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Job Application',
                'verbose_name_plural': 'Job Applications',
                'ordering': ['-created_at'],
            },
        ),
    ]
