# Generated by Django 5.2.5 on 2025-08-27 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_jobapplication'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('company', models.CharField(blank=True, max_length=200)),
                ('service', models.CharField(choices=[('Web Development', 'Web Development'), ('Mobile App Development', 'Mobile App Development'), ('Cloud Solutions', 'Cloud Solutions'), ('DevOps Consulting', 'DevOps Consulting'), ('AI/ML Implementation', 'AI/ML Implementation'), ('Blockchain Development', 'Blockchain Development'), ('Technical Consulting', 'Technical Consulting'), ('System Architecture', 'System Architecture')], max_length=100)),
                ('preferred_date', models.DateField()),
                ('preferred_time', models.CharField(max_length=20)),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rescheduled', 'Rescheduled')], default='pending', max_length=20)),
                ('duration', models.IntegerField(default=60)),
                ('meeting_link', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Appointment',
                'verbose_name_plural': 'Appointments',
                'ordering': ['-created_at'],
            },
        ),
    ]
