# Generated by Django 5.2.5 on 2025-08-27 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_appointment'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'confirmed'])), fields=('preferred_date', 'preferred_time'), name='unique_appointment_slot'),
        ),
    ]
