# Generated by Django 5.2.5 on 2025-08-28 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_appointment_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectestimation',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_estimations', to='api.company'),
        ),
        migrations.AlterField(
            model_name='projectestimation',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estimations', to='api.company'),
        ),
    ]
