# Generated by Django 4.2.7 on 2025-08-31 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_projectestimation_approved_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='calendar_created',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointment',
            name='google_calendar_event_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='google_calendar_id',
            field=models.CharField(blank=True, default='primary', max_length=500),
        ),
    ]
