# Generated by Django 4.2.7 on 2025-08-29 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0015_alter_projectestimation_approved_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobapplication",
            name="cv_parse_error",
            field=models.TextField(
                blank=True, help_text="Error message if CV parsing failed"
            ),
        ),
        migrations.AddField(
            model_name="jobapplication",
            name="cv_parse_success",
            field=models.BooleanField(
                default=False, help_text="Whether CV parsing was successful"
            ),
        ),
        migrations.AddField(
            model_name="jobapplication",
            name="cv_parsed_at",
            field=models.DateTimeField(
                blank=True, help_text="When CV was last parsed", null=True
            ),
        ),
        migrations.AddField(
            model_name="jobapplication",
            name="cv_text_preview",
            field=models.TextField(
                blank=True, help_text="First 2000 chars of extracted CV text"
            ),
        ),
        migrations.AddField(
            model_name="jobapplication",
            name="parsed_education",
            field=models.TextField(blank=True, help_text="Education extracted from CV"),
        ),
        migrations.AddField(
            model_name="jobapplication",
            name="parsed_email",
            field=models.EmailField(
                blank=True, help_text="Email extracted from CV", max_length=254
            ),
        ),
        migrations.AddField(
            model_name="jobapplication",
            name="parsed_experience_years",
            field=models.CharField(
                blank=True,
                help_text="Experience years extracted from CV",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="jobapplication",
            name="parsed_linkedin",
            field=models.URLField(blank=True, help_text="LinkedIn extracted from CV"),
        ),
        migrations.AddField(
            model_name="jobapplication",
            name="parsed_name",
            field=models.CharField(
                blank=True, help_text="Name extracted from CV", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="jobapplication",
            name="parsed_phone",
            field=models.CharField(
                blank=True, help_text="Phone extracted from CV", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="jobapplication",
            name="parsed_skills",
            field=models.TextField(
                blank=True, help_text="Skills extracted from CV (JSON format)"
            ),
        ),
        migrations.AddField(
            model_name="jobapplication",
            name="parsed_summary",
            field=models.TextField(
                blank=True, help_text="Professional summary extracted from CV"
            ),
        ),
    ]
