# Generated by Django 4.2.7 on 2025-08-31 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_add_google_calendar_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='service',
            field=models.CharField(choices=[('Free Consultation (30 min)', 'Free Consultation (30 min)'), ('Web Development', 'Web Development'), ('Mobile App Development', 'Mobile App Development'), ('Cloud Solutions', 'Cloud Solutions'), ('DevOps Consulting', 'DevOps Consulting'), ('AI/ML Implementation', 'AI/ML Implementation'), ('Blockchain Development', 'Blockchain Development'), ('Technical Consulting', 'Technical Consulting'), ('System Architecture', 'System Architecture')], max_length=100),
        ),
    ]
